### ISSUE TITLE
[Bug] Login fail

### ISSUE THREAD

**Issue by guydht** [PolyMeilex/node-myanimelist#11]
Hey
I'm trying to use this package in my electron app and the login method of ScraperClient keeps throwing an error "Tokens Not Found"
I looked around the code and found out it's because MAL doesn't send the "set-cookie" header - which is weird (?)

I'm pretty sure they (MAL) changed their behavior on logins because if I go to the website to the login page itself and clear my cookies I can't login unless I go first to the homepage (that means it sends the "set-cookie" header in the homepage?)

**Comment by guydht** [comment]
Seems like a bug on Myanimelist's side, since I got it working now....
Nevermind!

**Comment by PolyMeilex** [comment]
Thanks for the info anyway, MAL's login.php is a little bit unstable sometimes.

If you decide to continue your work, I would be happy to revive the MAL functions, because actually, I was planning to remove it because of a lack of interest in it (everyone just uses Jikan functions). But if you have some serious plans for your app, I would be happy to provide a solid scraper for it. There is a lot of endpoints that can be added + login still can be improved by a lot since it is in a prototype state. If you have any propositions or questions about mal inner workings let me know. It's fine to create an issue here even if it is not node-mal related.
